### ISSUE TITLE
三星s8 & s9 安卓8.0 模组管理器无限闪退

### ISSUE THREAD

**Issue by adfnkjasd** [xausky/UnityModManager#26]
![c4d96425ab18972bf2741b90eacd7b899f510a69](https://user-images.githubusercontent.com/39746646/40685314-806a1c12-63c6-11e8-9c44-16e52152cba4.jpg)
首先感谢作者做出这么好的软件，安卓7.0的时候用的非常舒服，8.0以后就出现问题了，能不能修复一下呢

**Comment by xausky** [comment]
现在这个的问题是我无法重现这个问题在我这里，我没有三星 安卓8.0的手机，我的一加3T也是8.0没有问题，我测试过8.0和8.1的安卓虚拟机也没有问题。

**Comment by Judgeming** [comment]
三星Note 8 也是同样问题

**Comment by Judgeming** [comment]
2.3.1使用持久化补丁选项后解决了问题，感谢更新

**Comment by MWSMXW** [comment]
s9也是

**Comment by xausky** [comment]
你们可以帮我使用这个项目：https://github.com/android-hacker/VirtualXposed
进行测试么，如果可以的话我可以尝试使用这个项目的VA内核。
@adfnkjasd @Judgeming

**Comment by MWSMXW** [comment]
没问题


发送自我的三星盖乐世智能手机。
-------- 原始信息 --------由： xausky <notifications@github.com> 日期: 2018/7/2  15:28  (GMT+08:00) 收件人： xausky/UnityModManager <UnityModManager@noreply.github.com> 抄送： 惊蛰 <764172745@qq.com>, Comment <comment@noreply.github.com> 主题： Re: [xausky/UnityModManager] 三星s8 & s9 安卓8.0 模组管理器无限闪退 (#26) 
你们可以帮我使用这个项目：https://github.com/android-hacker/VirtualXposed

进行测试么，如果可以的话我可以尝试使用这个项目的VA内核。

@adfnkjasd @Judgeming

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xausky/UnityModManager","title":"xausky/UnityModManager","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/xausky/UnityModManager"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xausky in #26: 你们可以帮我使用这个项目：https://github.com/android-hacker/VirtualXposed\r\n进行测试么，如果可以的话我可以尝试使用这个项目的VA内核。\r\n@adfnkjasd @Judgeming "}],"action":{"name":"View Issue","url":"https://github.com/xausky/UnityModManager/issues/26#issuecomment-401696177"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/xausky/UnityModManager/issues/26#issuecomment-401696177",
"url": "https://github.com/xausky/UnityModManager/issues/26#issuecomment-401696177",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [xausky/UnityModManager] 三星s8 \u0026 s9 安卓8.0 模组管理器无限闪退 (#26)",
"sections": [
{
"text": "",
"activityTitle": "**xausky**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@xausky",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"xausky/UnityModManager\",\n\"issueId\": 26,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"xausky/UnityModManager\",\n\"issueId\": 26\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/xausky/UnityModManager/issues/26#issuecomment-401696177"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 340320143\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by naloder** [comment]
@xausky 嘛。。以前就想提醒使用这个的内核试试了:stuck_out_tongue_closed_eyes:

**Comment by xausky** [comment]
但是需要测试表明这个内核比现在用的好，而且这个最低支持安卓5.0，无法在模拟器是使用，得做修改或者兼容才行。

**Comment by MWSMXW** [comment]
需要怎么弄

**Comment by Judgeming** [comment]
在virtualxposed允许安装无签名应用后，可以安装由模组管理器生成的崩坏3apk。可以登陆帐号，无法进入游戏，显示:"您安装的apk不是官方的包，点击确定跳转下载"

**Comment by xausky** [comment]
首先你的设备使用现在的模组管理器有问题么？
有的话你试试下载那个项目release里面的apk然后安装，然后用它运行崩坏3，然后如果没有问题我就用它的内核做一个模组管理器，然后你再测试这个管理器是不是正常。

**Comment by MWSMXW** [comment]
那个 我好像两边都无法使用

**Comment by adfnkjasd** [comment]
@xausky @Judgeming 应该是三星的虚拟环境有问题 我用VA装上以后会残留证书，卸载后无法安装正常的安装包，用模拟器安装模组管理器加载mod，导出整合包后用自己的jdk签名以后能正常安装，所以可能不是内核的问题

**Comment by Judgeming** [comment]
@adfnkjasd 求解如何用自己的jdk签名，多谢

**Comment by adfnkjasd** [comment]
@xausky 很正常啊，没有提示非官方应用
![screenshot_20180703-152935_ 3](https://user-images.githubusercontent.com/39746646/42205080-ffc44bde-7ed5-11e8-8807-1cd59303f27e.jpg)

**Comment by xausky** [comment]
可能是渠道服，官方会提示

**Comment by adfnkjasd** [comment]
我是官服的

**Comment by xausky** [comment]
不应该啊，官服会检查签名的

**Comment by adfnkjasd** [comment]
是不是跟跨服包有关系，我是ios的，用的跨服包

**Comment by xausky** [comment]
恩，那应该是，跨服包处理应该和渠道服一样。

**Comment by xausky** [comment]
@MWSMXW 两边无法使用的形式一样么，比如都是启动时候崩溃？

**Comment by MWSMXW** [comment]
不一样 非虚拟机这边提示停止运行，虚拟机一直等待然后卡死过一下又好了，然后无事发生。

**Comment by adfnkjasd** [comment]
@xausky 模组管理器启动游戏时崩溃 VirtualXposed启动正常

**Comment by xoxo360** [comment]
大佬，三星8.0，2.41模组管理器 IOS apk 也是一样报错。大佬可有解决办法吗，不想装集成好的~~

**Comment by xoxo360** [comment]
@xausky

**Comment by adfnkjasd** [comment]
@xoxo360 你是ios跨服嘛？

**Comment by xoxo360** [comment]
@adfnkjasd 对啊，IOS跨服包

**Comment by adfnkjasd** [comment]
@xoxo360 先用电脑上的模拟器安装模组管理器，然后装上你喜欢的mod导出整合包，签名以后就能用了

**Comment by adfnkjasd** [comment]
@xoxo360 签名我上面有说怎么弄0w0

**Comment by xoxo360** [comment]
@adfnkjasd 我的意思是不能自由换吗？

**Comment by adfnkjasd** [comment]
@xoxo360 是啊，不过签名也好弄，碰见别的喜欢的再导出签名安装就好咯

**Comment by xoxo360** [comment]
@adfnkjasd 大佬是只有三星有这个问题，还是所有IOS服包都有这个问题，大不了换vivo nex

**Comment by adfnkjasd** [comment]
应该是只有三星有问题，我用别的8.0测试都没什么问题

**Comment by xoxo360** [comment]
@adfnkjasd 7.0有问题吗。大不了我降级去？

**Comment by adfnkjasd** [comment]
@xoxo360 7.0没问题

**Comment by xoxo360** [comment]
@adfnkjasd @xausky 我查下怎么抓异常的方法把。有的话就贴出来

**Comment by xoxo360** [comment]
@xausky 
是这个吗？
com.samsung.android.app.cocktailbars[...]ktailbarservice.CocktailBarService#0
07-06 00:28:49.659   653   653 I SurfaceFlinger: 
07-06 00:28:49.706  3245  3786 I WindowManager: Destroying surface Surface(name=Application Error: io.github.xausky.unitymodmanager) called by com.android.server.wm.WindowStateAnimator.destroySurface:2465 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:967 com.android.server.wm.WindowState.destroyOrSaveSurfaceUnchecked:3651 com.android.server.wm.RootWindowContainer.performSurfacePlacement:818 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:233 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:168 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:158 com.android.server.wm.WindowSurfacePlacer.lambda$-com_android_server_wm_WindowSurfacePlacer_6459:135 
07-06 00:28:49.707   653  1393 I SurfaceFlinger: id=17214 Removed Application Error: io.github.xausky.unitymodmanager#0 (6/9)
07-06 00:28:49.707   653  1393 I SurfaceFlinger: id=17214 Removed Application Error: io.github.xausky.unitymodmanager#0 (-2/9)
07-06 00:28:49.707  3245  3786 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
07-06 00:28:49.720   653   653 I Layer   : id=17214 onRemoved Application Error: io.github.xausky.unitymodmanager#0 
07-06 00:28:49.749  5193  6446 I AsyncOpDispatcher: 35-GetDeviceDataUploadOptInStatusOperation
07-06 00:28:49.750 26117 26117 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object mirror.RefObject.get(java.lang.Object)' on a null object reference
07-06 00:28:49.750 26117 26117 W System.err: 	at com.lody.virtual.client.hook.proxies.clipboard.ClipBoardStub.getInterface(ClipBoardStub.java:29)
07-06 00:28:49.750 26117 26117 W System.err: 	at com.lody.virtual.client.hook.proxies.clipboard.ClipBoardStub.<init>(ClipBoardStub.java:22)
07-06 00:28:49.750 26117 26117 W System.err: 	at com.lody.virtual.client.core.InvocationStubManager.injectInternal(InvocationStubManager.java:130)
07-06 00:28:49.750 26117 26117 W System.err: 	at com.lody.virtual.client.core.InvocationStubManager.init(InvocationStubManager.java:105)
07-06 00:28:49.750 26117 26117 W System.err: 	at com.lody.virtual.client.core.VirtualCore.startup(VirtualCore.java:198)
07-06 00:28:49.750 26117 26117 W System.err: 	at io.github.xausky.unitymodmanager.MainApplication.attachBaseContext(MainApplication.java:22)
07-06 00:28:49.750 26117 26117 W System.err: 	at android.app.Application.attach(Application.java:213)
07-06 00:28:49.750 26117 26117 W System.err: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1109)
07-06 00:28:49.750 26117 26117 W System.err: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1093)
07-06 00:28:49.750 26117 26117 W System.err: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:973)
07-06 00:28:49.750 26117 26117 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6030)
07-06 00:28:49.750 26117 26117 W System.err: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
07-06 00:28:49.750 26117 26117 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
07-06 00:28:49.750 26117 26117 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-06 00:28:49.750 26117 26117 W System.err: 	at android.os.Looper.loop(Looper.java:164)
07-06 00:28:49.750 26117 26117 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6938)
07-06 00:28:49.750 26117 26117 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
07-06 00:28:49.750 26117 26117 W System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
07-06 00:28:49.750 26117 26117 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
07-06 00:28:49.751 26117 26117 D AndroidRuntime: Shutting down VM
07-06 00:28:49.751 26117 26117 E AndroidRuntime: FATAL EXCEPTION: main
07-06 00:28:49.751 26117 26117 E AndroidRuntime: Process: io.github.xausky.unitymodmanager:p0, PID: 26117
07-06 00:28:49.751 26117 26117 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application io.github.xausky.unitymodmanager.MainApplication: java.lang.RuntimeException: virtual app core startup failed:Attempt to invoke virtual method 'java.lang.Object mirror.RefObject.get(java.lang.Object)' on a null object reference
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:979)
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6030)
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6938)
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
07-06 00:28:49.751 26117 26117 E AndroidRuntime: Caused by: java.lang.RuntimeException: virtual app core startup failed:Attempt to invoke virtual method 'java.lang.Object mirror.RefObject.get(java.lang.Object)' on a null object reference
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	at io.github.xausky.unitymodmanager.MainApplication.attachBaseContext(MainApplication.java:25)
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	at android.app.Application.attach(Application.java:213)
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1109)
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1093)
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:973)
07-06 00:28:49.751 26117 26117 E AndroidRuntime: 	... 9 more
07-06 00:28:49.753  3245  5431 D AppErrorSuggester: Not install apperror suggest center
07-06 00:28:49.753  3245  5431 D AppErrorSuggester: suggest code:0
07-06 00:28:49.753  3245  5431 D Debug   : !@DumpState : SHIP
07-06 00:28:49.753  3245  5431 D Debug   : !@DumpState : debug level:0x4f4c
07-06 00:28:49.753  3245  5431 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
07-06 00:28:49.753  3245  5431 W ActivityManager: crash : io.github.xausky.unitymodmanager,0
07-06 00:28:49.756 24125 24125 I DMT-SMReceiver: Received : com.samsung.android.sm.ACTION_ERROR
07-06 00:28:49.756  3245  3363 I ActivityManager: Showing crash dialog for package io.github.xausky.unitymodmanager u0
07-06 00:28:49.756 24125 24125 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1483 android.content.ContextWrapper.startService:663 android.content.ContextWrapper.startService:663 com.samsung.android.sm.common.SmartManagerReceiver.a:226 com.samsung.android.sm.common.SmartManagerReceiver.onReceive:111 
07-06 00:28:49.759  3245  3363 D ScrollView: initGoToTop
07-06 00:28:49.763  3245  3363 D RestrictionPolicy: isGoogleCrashReportAllowed : ret=true userId =0
07-06 00:28:49.765  3245  3363 E PhoneWindow_APM : : sendNotificationForAppPermissionMonitor callingPid = 3245, uid = 1000
07-06 00:28:49.765  3245  3363 E PhoneWindow_APM : : sendNotificationForAppPermissionMonitor 2
07-06 00:28:49.765  3245  3363 E PhoneWindow_APM : : sendNotificationForAppPermissionMonitor 21000_3245
07-06 00:28:49.765  3245  3363 E PhoneWindow_APM : : isCalledPackage return true
07-06 00:28:49.766  3245  3416 V MARsPolicyManager: handelAlertToastWindowStarted pkgName = android, userId = 0
07-06 00:28:49.768  3245  3363 D InputDispatcher: Focus left window: 25763
07-06 00:28:49.768  3245  3363 D InputDispatcher: Focus entered window: 3245
07-06 00:28:49.768  3245  3363 D ViewRootImpl@7a2ce6b[unitymodmanager]: setView = DecorView@b851e61[unitymodmanager] TM=true MM=false
07-06 00:28:49.771  3245  3363 D ViewRootImpl@7a2ce6b[unitymodmanager]: dispatchAttachedToWindow
07-06 00:28:49.772  3245  3363 V WindowManager: Relayout Window{cf8adc8 u0 Application Error: io.github.xausky.unitymodmanager}: viewVisibility=0 req=1014x393 WM.LayoutParams{(0,0)(wrapxwrap) gr=#11 sim=#120 ty=2003 fl=#1820002 pfl=0x1000110 fmt=-3 wanim=0x10302ec vsysui=0x10 surfaceInsets=Rect(6, 6 - 6, 6) needsMenuKey=2 colorMode=0 naviIconColor=0}
07-06 00:28:49.776   653   653 I SurfaceFlinger: id=17215 createSurf (1026x405),1 flag=4, Application Error: io.github.xausky.unitymodmanager#0
07-06 00:28:49.778 24125 26136 V CrashedAppLogging: isMasterSwitchOff : false
07-06 00:28:49.779  3245  3363 V Surface : sf_framedrop debug : 0x4f4c, game : false, logging : 0
07-06 00:28:49.782 24662 24676 E SQLiteLog: (1) no such table: scpm_bad_app
07-06 00:28:49.783 24662 24676 E DatabaseUtils: Writing exception to parcel
07-06 00:28:49.783 24662 24676 E DatabaseUtils: android.database.sqlite.SQLiteException: no such table: scpm_bad_app (code 1): , while compiling: SELECT errorType, verCode, verName, modelInfo, isFixed, fixedVersion FROM scpm_bad_app WHERE (pName = ? AND verCode = ? AND isIgnored = ?)
07-06 00:28:49.783 24662 24676 E DatabaseUtils: #################################################################
07-06 00:28:49.783 24662 24676 E DatabaseUtils: Error Code : 1 (SQLITE_ERROR)
07-06 00:28:49.783 24662 24676 E DatabaseUtils: Caused By : SQL(query) error or missing database.
07-06 00:28:49.783 24662 24676 E DatabaseUtils: 	(no such table: scpm_bad_app (code 1): , while compiling: SELECT errorType, verCode, verName, modelInfo, isFixed, fixedVersion FROM scpm_bad_app WHERE (pName = ? AND verCode = ? AND isIgnored = ?))
07-06 00:28:49.783 24662 24676 E DatabaseUtils: #################################################################

**Comment by xausky** [comment]
这个版本使用VirtualXposed项目的虚拟环境内核，希望有人帮助测试看看：https://github.com/xausky/UnityModManager/releases/tag/v2.5.0-dev

**Comment by Judgeming** [comment]
2.5.0版本note8可以完美运行游戏!感谢大佬更新!

**Comment by mingyuS1** [comment]
2.5三星s9+完美运行，感谢作者！

**Comment by xausky** [comment]
那应该是解决了，过段时间会发布2.5正式版。
